baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Kubernetes Community"
theme = "docdock"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
publishDir="build/public"

[params]
editURL = ""
showVisitedLinks = true # default is false
themeStyle = "original" # "original" or "flex" # default "flex"
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "title" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = true # default is false
disableNavChevron = true # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true
# custom_css = [] #ordered list to override css

[outputs]
home = [ "HTML", "RSS", "JSON"]

# items in main will default to being ordered above auto-generated content and NOT open in new page
[[menu.main]]
name = "Community Membership"
url = "/community-membership/"

[[menu.main]]
name = "Governance"
url = "/governance/"

[[menu.main]]
name = "SIG governance"
url = "/sig-governance/"
#
# [[menu.shortcut   s]]
# shortcuts assumes going offsite and will open in a few window
