baseURL = "https://www.kubernetes.dev/"
title = "Kubernetes Contributors"

theme = ["docsy"]
themesDir = "node_modules"
enableRobotsTXT = true

# Language settings
contentDir = "content/en"
enableMissingTranslationPlaceholders = true
disableKinds = ["taxonomy"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"

[services]
  [services.googleAnalytics]
  # Fake ID in support of [params.ui.feedback]. The real GA ID is set in the Netlify config.
  id = "UA-00000000-0"

# Hugo internal caching
[caches]
  [caches.assets]
    dir = ":cacheDir/_gen"
    maxAge = -1
  [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "60s"
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "60s"
  [caches.images]
    dir = ":cacheDir/_images"
    maxAge = -1
  [caches.modules]
    dir = ":cacheDir/modules"
    maxAge = -1

# Language configuration
[languages]
  [languages.en]
    title = "Kubernetes Contributors"
    languageName = "English"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  # Default highlight is tango for Docsy but the website uses emacs (for now)
  [markup.highlight]
    style = "emacs"

[frontmatter]
  date = ["date", ":filename", "publishDate", "lastmod"]

# Everything below this are Site Params
[params]
  # This is used instead of the built-in top level `copyright` to utilize
  # Docsy's partial which adds the copyright year automatically
  copyright = "The Kubernetes Authors"
  gcs_engine_id = "8ad0f1b8442fece81"

  # User interface configuration
  [params.ui]
    # Enable to show the sidebar menu in its compact state.
    sidebar_menu_compact = true
    # Set to true to disable the About link in the site footer
    footer_about_disable = false

    # Adds an H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
    # This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
    # If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
    # add "hide_feedback: true" to the page's front matter.
    [params.ui.feedback]
      enable = true
    # The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
    # yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
    # no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

  [params.links]
    # End user relevant links. These will show up on left side of footer and in the community page if you have one.
    [[params.links.user]]
      name = "Kubernetes Dev Mailing List"
      url = "https://groups.google.com/a/kubernetes.io/group/dev"
      icon = "fa fa-envelope"
      desc = "Discussion and help from your fellow users"
    [[params.links.user]]
      name = "Twitter"
      url = "https://twitter.com/K8sContributors"
      icon = "fab fa-twitter"
      desc = "Follow us on Twitter to get the latest news!"
    [[params.links.user]]
      name = "LinkedIn"
      url = "https://www.linkedin.com/company/kubernetes"
      icon = "fab fa-linkedin"
      desc = "Kubernetes on LinkedIn"
    
    # Developer relevant links. These will show up on right side of footer and in the community page if you have one.
    [[params.links.developer]]
      name = "GitHub"
      url = "https://github.com/kubernetes/community"
      icon = "fab fa-github"
      desc = "Home of the Kubernetes Community!"
    [[params.links.developer]]
      name = "Slack"
      url = "https://slack.k8s.io"
      icon = "fab fa-slack"
      desc = "Chat with other project developers"
